import Head from 'next/head';

import Lottie from 'react-lottie';
import styled from 'styled-components';
import Card from '../../components/Card';

import CardContainer from '../../components/CardContainer';
import Footer from '../../components/Footer';
import Header from '../../components/Header';

import * as bookLoadingAnim from '../../lottie/book_loading.json';
import AbstractLogo from '../../public/abstract_1.svg';
import AbstractLogo2 from '../../public/abstract_2.svg';
import Wrapper from '../../components/Wrapper';

import dynamic from 'next/dynamic';

const NoSSRGlassChart = dynamic(() => import('../../components/GlassChart'), {
  ssr: false,
});

const bookLoadingAnimOptions = {
  loop: true,
  autoplay: true,
  animationData: bookLoadingAnim,
  rendererSettings: {
    preserveAspectRatio: 'xMidYMid slice',
  },
};

const Charts = styled.div`
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 1rem;
  min-height: 50vh;
  h2 {
    /* dont wrap text */
    font-size: 2rem;
    white-space: nowrap;
  }
  background: rgba(255, 255, 255, 0.25);
  box-shadow: 0 8px 32px 0 rgba(31, 38, 135, 0.37);
  backdrop-filter: blur(7.5px);
  -webkit-backdrop-filter: blur(7.5px);
  border-radius: 10px;
  border: 1px solid rgba(255, 255, 255, 0.18);
  @media screen and (max-width: 768px) {
    flex-direction: column;
    padding: 0.2rem;
  }
`;

const Container = styled.div`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  padding: 1rem 1.5rem;
  min-height: 100vh;
  background: linear-gradient(360deg, #b9fbff 0%, #d1c9f1 100%);
  @media screen and (max-width: 768px) {
    padding: 0.5rem;
  }
`;

const Page = () => {
  return (
    <>
      <Header />
      <Container>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Wrapper
          title="To Learn"
          content={
            <CardContainer>
              <Card />
              <Card />
              <Card />
            </CardContainer>
          }
          background={<AbstractLogo2 />}
        />
        <Wrapper
          content={
            <Charts>
              <h2>Some stats 😋</h2>
              <NoSSRGlassChart />
            </Charts>
          }
          background={<AbstractLogo />}
        />
      </Container>
      <Footer />
    </>
  );
};

export default Page;

/* <Lottie
        options={bookLoadingAnimOptions}
        height={'50vw'}
        width={'50vw'}
        isStopped={true}
        isPaused={false}
      /> */
