import Head from 'next/head';
import { useState } from 'react';
import Lottie from 'react-lottie';
import styled from 'styled-components';
import Card from '../../components/Card';
import { AwesomeButton } from 'react-awesome-button';
import * as bookLoadingAnim from '../../lottie/book_loading.json';
import Image from 'next/image';
import { useRouter } from 'next/router';
import { useGoogleLogin } from 'react-google-login';
import { CLIENT_ID } from '../login/google/config';

import Logout from '../login/google/Logout';
const bookLoadingAnimOptions = {
  loop: true,
  autoplay: true,
  animationData: bookLoadingAnim,
  rendererSettings: {
    preserveAspectRatio: 'xMidYMid slice',
  },
};

const Container = styled.div`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  padding: 1rem 1.5rem;
  background: linear-gradient(360deg, #b9fbff 0%, #d1c9f1 100%);
`;

const Page = () => {
  const [profile, setProfile] = useState();
  const router = useRouter();
  useGoogleLogin({
    clientId: CLIENT_ID,
    isSignedIn: true,
    fetchBasicProfile: true,
    onSuccess: (res) => {
      setProfile(res.profileObj);
    },
  });
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>
        Hello &nbsp;
        {profile && profile.name}
      </h1>
      {profile ? (
        <Logout
          clear={() => {
            setProfile(null);
          }}
        />
      ) : (
        <AwesomeButton onPress={() => router.push('/login')}>
          {' '}
          Login{' '}
        </AwesomeButton>
      )}
      <Lottie
        options={bookLoadingAnimOptions}
        height={'50vw'}
        width={'50vw'}
        isStopped={false}
        isPaused={false}
      />
      <Card />
    </Container>
  );
};

export default Page;
